apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: spark
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi