---
# Source: hadoop/templates/hdfs-dn-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-hadoop-hdfs-dn
  annotations:
    checksum/config: 21e27fb49b4b91504a85104eaf54cbc729d8729a419d4c276476f4bec9043f93
  labels:
    app: hadoop
    chart: hadoop-1.1.2
    release: hadoop
    component: hdfs-dn
spec:
  serviceName: hadoop-hadoop-hdfs-dn
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
      release: hadoop
      component: hdfs-dn
  template:
    metadata:
      labels:
        app: hadoop
        release: hadoop
        component: hdfs-dn
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  hadoop
                  release: "hadoop"
                  component: hdfs-dn
      terminationGracePeriodSeconds: 0
      containers:
      - name: hdfs-dn
        image: "danisla/hadoop:2.9.0"
        imagePullPolicy: "IfNotPresent"
        command:
           - "/bin/bash"
           - "/tmp/hadoop-config/bootstrap.sh"
           - "-d"
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 10m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 50075
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 50075
          initialDelaySeconds: 10
          timeoutSeconds: 2
        volumeMounts:
        - name: hadoop-config
          mountPath: /tmp/hadoop-config
        - name: dfs
          mountPath: /root/hdfs/datanode
      volumes:
      - name: hadoop-config
        configMap:
          name: hadoop-hadoop
      - name: dfs
        emptyDir: {}
