---
# Source: hadoop/templates/hdfs-nn-svc.yaml
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: hadoop-hadoop-hdfs-nn
  labels:
    app: hadoop
    chart: hadoop-1.1.2
    release: hadoop
    component: hdfs-nn
spec:
  ports:
  - name: dfs
    port: 9000
    protocol: TCP
  - name: webhdfs
    port: 50070
  clusterIP: None
  selector:
    app: hadoop
    release: hadoop
    component: hdfs-nn
