---
# Source: hadoop/templates/yarn-rm-svc.yaml
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: hadoop-hadoop-yarn-rm
  labels:
    app: hadoop
    chart: hadoop-1.1.2
    release: hadoop
    component: yarn-rm
spec:
  ports:
  - port: 8088
    name: web
  clusterIP: None
  selector:
    app: hadoop
    release: hadoop
    component: yarn-rm
